### PR TITLE
Upgraded tailwind classes to v1.0

### PR DESCRIPTION
**Pull request by rhorber**
I changed/added the CSS classes to version 1.0 according to [the upgrade guide](https://next.tailwindcss.com/docs/upgrading-to-v1/).

### CODE REVIEW

**Comment by aaemnnosttv** [comment]
Hey thanks! Would you mind updating the stylesheet to use the same one as the docs have now?
https://tailwindcss.com/docs/installation/#using-tailwind-via-cdn

**Comment by rhorber** [comment]
Of course not. I updated it :).

**Comment by rhorber** [comment]
Sorry, pressed the wrong button 😳

**Comment by aaemnnosttv** [comment]
Thank you! 💪

**Pull request merged**
